language: python
cache: pip

matrix:
  include:
    - python: "3.6"
    - python: "3.7"

before_install:
  - "sudo apt-get install graphviz"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=src --cov-config=.coveragerc tests
  - flake8

after_success:
  - codecov
